### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by myyan** [EOSIO/eosjs-ui#2]
```json
❌  Client build failed

Hash: a0b05710ea669cbf2d34
Version: webpack 2.6.1
Time: 4668ms
  Asset     Size  Chunks  Chunk Names
main.js  6.08 MB       0  main
chunk    {0} main.js (main) 2.24 MB [entry] [rendered]
   [13] ./~/react/react.js 56 bytes {0} [built]
   [19] ./~/mobx/lib/mobx.module.js 142 kB {0} [built]
   [30] (webpack)/buildin/global.js 509 bytes {0} [built]
  [120] ./~/mobx-react/index.js 29.7 kB {0} [built]
  [134] ./src/client/Root.js 1.13 kB {0} [built]
  [179] ./~/react-dom/index.js 63 bytes {0} [built]
  [313] ./src/client/index.js 1.77 kB {0} [built]
  [314] ./~/babel-polyfill/lib/index.js 833 bytes {0} [built]
  [315] ./~/react-hot-loader/patch.js 41 bytes {0} [built]
  [316] (webpack)-hot-middleware/client.js?reload=true&path=http://localhost:3001/__webpack_hmr 6.68 kB {0} [built]
  [659] ./~/querystring-es3/index.js 127 bytes {0} [built]
  [661] ./~/react-hot-loader/index.js 41 bytes {0} [built]
  [666] ./~/react-hot-loader/lib/patch.js 209 bytes {0} [built]
  [791] (webpack)-hot-middleware/process-update.js 3.88 kB {0} [built]
  [793] multi babel-polyfill react-hot-loader/patch webpack-hot-middleware/client?reload=true&path=http://localhost:3001/__webpack_hmr ./src/client/index.js 64 bytes {0} [built]
     + 779 hidden modules

ERROR in ./~/eosjs/lib/index.js
Module not found: Error: Can't resolve 'eosjs-ecc' in '/Users/code/eosjs-ui/node_modules/eosjs/lib'
 @ ./~/eosjs/lib/index.js 5:10-30
 @ ./src/components/Transfer/index.js
 @ ./src/routes/index.js
 @ ./src/client/Root.js
 @ ./src/client/index.js
 @ multi babel-polyfill react-hot-loader/patch webpack-hot-middleware/client?reload=true&path=http://localhost:3001/__webpack_hmr ./src/client/index.js
ERROR in ./~/eosjs/lib/structs.js
```

**Comment by myyan** [comment]
```bash
$ node -v
v8.5.0
```

**Comment by jcalfee** [comment]
Sorry, this is Deprecated .. this is for reference only.  I added a note to the README..

eosjs-ecc is at npm so `npm i eosjs-ecc` might work.

**Comment by littlefive** [comment]
npm run dev
after
.....
/work/eos/eosjs-ui/node_modules/eosjs/node_modules/babel-polyfill/lib/index.js:10
  throw new Error("only one instance of babel-polyfill is allowed");
        ^
Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (/Users/huqingping/work/eos/eosjs-ui/node_modules/eosjs/node_modules/babel-polyfill/lib/index.js:10:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/aa/work/eos/eosjs-ui/node_modules/eosjs/lib/index.js:5:1)
    at Module._compile (module.js:652:30)

please help me look at this error,Ths

**Comment by jcalfee** [comment]
Thanks for posting back .. I did need to patch eosjs to make this work better.  I took me a few tries, but eosjs-ui `npm run dev` started working again.    Make sure to run `npm i` again after pulling.
