### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by littlefive** [EOSIO/eosjs-ui#3]
npm run dev
after
.....
/work/eos/eosjs-ui/node_modules/eosjs/node_modules/babel-polyfill/lib/index.js:10
throw new Error("only one instance of babel-polyfill is allowed");
^
Error: only one instance of babel-polyfill is allowed
at Object. (/Users/huqingping/work/eos/eosjs-ui/node_modules/eosjs/node_modules/babel-polyfill/lib/index.js:10:9)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object. (/Users/aa/work/eos/eosjs-ui/node_modules/eosjs/lib/index.js:5:1)
at Module._compile (module.js:652:30)

please help me look at this error,Ths

**Comment by littlefive** [comment]
sorry, error is fixed....
need to "eosjs-ui/node_modules/eosjs/lib/index.js:5:1"  in index.js annotate require babel-polyfill codeline
